//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class IngredientMeasurementBase : EntityBase
    {
        public IngredientMeasurementBase()
        {
            this.FromIngredientMeasurementAlternates = new HashSet<IngredientMeasurementAlternate>();
            this.ToIngredientMeasurementAlternates = new HashSet<IngredientMeasurementAlternate>();
            this.RecipeIngredientMeasurements = new HashSet<RecipeIngredientMeasurement>();
        }
    
    	[System.ComponentModel.DataAnnotations.Schema.NotMapped]
    	public override int ID { get { return IngredientMeasurementID; } set { IngredientMeasurementID = value; } }
    
        [Key]
        public virtual int IngredientMeasurementID { get; set; }
        public virtual int IngredientID { get; set; }
        public virtual int? MeasurementID { get; set; }
        public virtual float? CaloriesPer { get; set; }
        public virtual float? CarbohydratesPer { get; set; }
        public virtual float? FatPer { get; set; }
        public virtual float? SaturatedFatPer { get; set; }
        public virtual float? SugarsPer { get; set; }
        public virtual float? ProteinPer { get; set; }
    
        public Ingredient Ingredient { get; set; }
        public Measurement Measurement { get; set; }
        public ICollection<IngredientMeasurementAlternate> FromIngredientMeasurementAlternates { get; set; }
        public ICollection<IngredientMeasurementAlternate> ToIngredientMeasurementAlternates { get; set; }
        public ICollection<RecipeIngredientMeasurement> RecipeIngredientMeasurements { get; set; }
    }
}
