//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class IngredientMeasurementAlternateBase : EntityBase
    {
        [Key]
        public virtual int IngredientMeasurementAlternateID { get; set; }
        public virtual int FromIngredientMeasurementID { get; set; }
        public virtual int ToIngredientMeasurementID { get; set; }
        public virtual float? Multiplier { get; set; }
    
        public IngredientMeasurement FromIngredientMeasurement { get; set; }
        public IngredientMeasurement ToIngredientMeasurement { get; set; }
    }
}
