//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class IngredientBase : EntityBase
    {
        public IngredientBase()
        {
            this.IngredientMeasurements = new HashSet<IngredientMeasurement>();
        }
    
    	[System.ComponentModel.DataAnnotations.Schema.NotMapped]
    	public override int ID { get { return IngredientID; } set { IngredientID = value; } }
    
        [Key]
        public virtual int IngredientID { get; set; }
        public virtual string IngredientName { get; set; }
    
        public ICollection<IngredientMeasurement> IngredientMeasurements { get; set; }
    
    	public override string ToString()
    	{
    		return IngredientName;
    	}
    }
}
