//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class RecipeIngredientMeasurementBase : EntityBase
    {
    	public virtual bool SaveIngredientMeasurement { get { return false; } }
    	public virtual bool SaveRecipe { get { return false; } }
        [Key]
        public virtual int RecipeIngredientMeasurementID { get; set; }
        public virtual int RecipeID { get; set; }
        public virtual int IngredientMeasurementID { get; set; }
        public virtual float? Quantity { get; set; }
        public virtual bool IsOptional { get; set; }
    
        public virtual IngredientMeasurement IngredientMeasurement { get; set; }
        public virtual Recipe Recipe { get; set; }
    }
}
