//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class RecipeBase : EntityBase
    {
        public RecipeBase()
        {
            this.RecipeImages = new HashSet<RecipeImage>();
            this.RecipeIngredientMeasurements = new HashSet<RecipeIngredientMeasurement>();
            this.UserRecipes = new HashSet<UserRecipe>();
        }
    
    	[System.ComponentModel.DataAnnotations.Schema.NotMapped]
    	public override int ID { get { return RecipeID; } set { RecipeID = value; } }
    
        [Key]
        public virtual int RecipeID { get; set; }
        public virtual string RecipeName { get; set; }
        public virtual string Directions { get; set; }
        public virtual int? NumberOfServings { get; set; }
        public virtual float? Rating { get; set; }
        public virtual bool Inactive { get; set; }
        public virtual string RecipeURL { get; set; }
        public virtual int? RecipeSourceID { get; set; }
        public virtual PaJaMa.Recipes.Model.RecipeType RecipeType { get; set; }
    	public string RecipeTypeString { get { return EnumHelper.GetEnumDisplay<PaJaMa.Recipes.Model.RecipeType>(RecipeType); } }
    
        public RecipeSource RecipeSource { get; set; }
        public ICollection<RecipeImage> RecipeImages { get; set; }
        public ICollection<RecipeIngredientMeasurement> RecipeIngredientMeasurements { get; set; }
        public ICollection<UserRecipe> UserRecipes { get; set; }
    
    	public override string ToString()
    	{
    		return RecipeName;
    	}
    }
}
