//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class RecipeSourceBase : EntityBase
    {
        public RecipeSourceBase()
        {
            this.Recipes = new HashSet<Recipe>();
        }
    
    	[System.ComponentModel.DataAnnotations.Schema.NotMapped]
    	public override int ID { get { return RecipeSourceID; } set { RecipeSourceID = value; } }
    
        [Key]
        public virtual int RecipeSourceID { get; set; }
        public virtual string RecipeSourceName { get; set; }
    
        public ICollection<Recipe> Recipes { get; set; }
    
    	public override string ToString()
    	{
    		return RecipeSourceName;
    	}
    }
}
