//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Entities.Base
{
    using System;
    using System.Collections.Generic;
    
    using System.Linq;
    
    using PaJaMa.Common;
    using PaJaMa.Data;
    
    using System.ComponentModel.DataAnnotations;
        
    public abstract class UserBase : EntityBase
    {
        public UserBase()
        {
            this.UserRecipes = new HashSet<UserRecipe>();
        }
    
    	[System.ComponentModel.DataAnnotations.Schema.NotMapped]
    	public override int ID { get { return UserID; } set { UserID = value; } }
    
        [Key]
        public virtual int UserID { get; set; }
        public virtual string UserName { get; set; }
        public virtual string Password { get; set; }
    
        public ICollection<UserRecipe> UserRecipes { get; set; }
    
    	public override string ToString()
    	{
    		return UserName;
    	}
    }
}
