//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaJaMa.Recipes.Model.Dto.Base
{
    using PaJaMa.Common;
    using PaJaMa.Data;
    using System;
    using System.Collections.Generic;
    
    public abstract class UserRecipeDtoBase : EntityDtoBase
    {
        public virtual bool IsBookmarked { get; set; }
        public virtual Nullable<float> Rating { get; set; }
        public virtual string Notes { get; set; }
        public virtual bool AllowEdit { get; set; }
    	
    	// must be overridden to be exposed
        // public virtual RecipeDto Recipe { get; set; }
        // public virtual UserDto User { get; set; }
    
    	public override string ToString()
    	{
    		return Notes;
    	}
    }
}
